
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvrhytzvodxdsgnlusuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cmh5dHp2b2R4ZHNnbmx1c3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODgwMzMsImV4cCI6MjA2MzM2NDAzM30._KCfegTKjHsDe6dFAdFlxhTYnIzqMK3PaqfyR3q_PDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
